services:
  postgres:
    image: postgres:13.10
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres_db_aio" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  migration:
    build: .
    env_file: .env
    depends_on:
      - postgres
    command: >
      sh -c "sleep 30 && alembic upgrade head"

  bot:
    build: .
    container_name: aio_bot
    depends_on:
      - postgres
      - redis
    env_file: .env
    restart: unless-stopped
    


volumes:
  pg_data:
